// app/layout.tsx

import './globals.css'
import { ReactNode } from 'react'
import { Metadata } from 'next'
import { HeroHeader } from '@/components/header'
import HeroSection from '@/components/hero-section'
import FeaturesSection from '@/components/features-8'
import ContentSection from '@/components/content-2'
import FooterSection from '@/components/footer'
import FAQsTwo from '@/components/faqs-2'

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <HeroHeader />
        <HeroSection />
        <FeaturesSection />
        <FAQsTwo /> 
        <FooterSection />
      </body>
    </html>
  )
}
